from pilotCore import conversation
# CallbackQueryHandler data:


# Customer main page:
# Back:
TO_CUSTOMER_MAIN_CB = 'TO_CUSTOMER_MAIN_CB'

LIST_ROUTES_CB = 'LIST_ROUTES_CB'
SET_ROUTE_ALERT_CB = 'SET_ROUTE_ALERT_CB'
CUSTOMER_PROPERTIES_CB = 'CUSTOMER_PROPERTIES_CB'


# Customer list routes page:
ROUTES_NEXT_RIDE = 'ROUTES_NEXT_RIDE_CB'
ROUTES_PREV_RIDE = 'ROUTES_PREV_RIDE_CB'
ROUTES_DYNAMIC_CB_RIDE = 'ROUTES_DYNAMIC_CB_RIDE'
ROUTES_CB_PREFIX = 'routest_cb'
routes_dynamic_callback_patt = [f'^{ROUTES_CB_PREFIX}:{i}$|' for i in range(50)]
ROUTES_DYNAMIC_CB_RIDE_PATT = ''.join(routes_dynamic_callback_patt)
ROUTES_DYNAMIC_CB_RIDE = [f'{ROUTES_CB_PREFIX}:{i}' for i in range(50)]
ROUTES_SELECT_BUTTON_CB = 'ROUTES_SELECT_BUTTON_CB'



# Customer preference page:
# CallBack simmilar to Customer model field names for customer_properties.
CUSTOMER_SET_NAME_CB = 'REAL_NAME_CB'
CUSTOMER_SET_NUMBER_CB = 'MOBILE_NUMBER_CB'
# Redirection patterns:
REPLY_HANDLESR = [
    CUSTOMER_SET_NAME_CB,
    CUSTOMER_SET_NUMBER_CB
]

CONVERSATION_REDIRECT = {
    CUSTOMER_SET_NAME_CB: conversation.CUSTOMER_SET_NAME_CONV,
    CUSTOMER_SET_NUMBER_CB: conversation.CUSTOMER_SET_NUMBER_CONV
}


# Select seats:
CUSTOMER_SELECT_SEATS_PLUS_CB = 'CUSTOMER_SELECT_SEATS_PLUS_CB'
CUSTOMER_SELECT_SEATS_NUM_CB = 'CUSTOMER_SELECT_SEATS_NUM_CB'
CUSTOMER_SELECT_SEATS_MINUS_CB = 'CUSTOMER_SELECT_SEATS_MINUS_CB'

CUSTOMER_SELECT_SEATS_CONFIRM_CB = 'CUSTOMER_SELECT_SEATS_CONFIRM_CB'

CUSTOMER_RIDE_CONFIRM_CB = 'CUSTOMER_RIDE_CONFIRM_CB'